package assets.virologist.behavior.learnhevior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.learnhevior.LearnBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;

/** The field.virologist.behavior which decides if the field.virologist.Virologist can learn a collectables.genome.Genome */
public interface LearnBehavior {
	/**
	 *
	 * @param v the field.virologist.Virologist who wants to learn the collectables.genome.Genome
	 */
	void Learn(Virologist v);
}
