package assets.virologist.behavior.learnhevior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.learnhevior.NotLearn.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;
import main.Skeleton;
public class NotLearn implements LearnBehavior {
    /**
     * Nothing happens
     *
     * @param v the field.virologist.Virologist who wants to learn the collectables.genome.Genome
     */
    @Override
    public void Learn(Virologist v) {
        Skeleton.methodCall(this, "v");
        Skeleton.methodReturn(this);
    }
}
