package assets.virologist.behavior.movebehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.movebehavior.Move.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.field.Field;
import assets.virologist.*;
import main.Skeleton;

public class Move implements MoveBehavior {
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 0;
    }

    /**
     * The field.virologist.Virologist finds the field.field.Field on the desired direction and steps on it.
     *
     * @param v the field.virologist.Virologist who tries to move
     * @param d the direction he wants to move
     */
    //TODO
    @Override
    public void MoveToField(Virologist v, int d) {
        Skeleton.methodCall(this, "v", "d");
        Field f = v.GetRoute().GetLocation();
        Field f2 = f.GetNeighbour(d);
        f.Remove(v);
        f2.Accept(v);
        v.GetRoute().Add(f2);
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
