package assets.virologist.behavior.movebehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.movebehavior.NotMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.State;
import assets.virologist.Virologist;
import main.Skeleton;
public class NotMove implements MoveBehavior, java.io.Serializable {
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 2;
    }

    /**
     * Nothing happens. The Virologist can not move.
     *
     * @param v the field.virologist.Virologist who tries to move
     * @param d the direction he wants to move
     */
    @Override
    public void MoveToField(Virologist v, int d) {
        Skeleton.methodCall(this, "v", "d");
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
