package assets.virologist.behavior.movebehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.movebehavior.RandomMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.field.Field;
import assets.virologist.State;
import assets.virologist.Virologist;
import assets.virologist.behavior.learnbehavior.NotLearn;

import java.util.ArrayList;
import main.Skeleton;
public class RandomMove implements MoveBehavior {
    /**
     * Generates a random number between to numbers.
     * Both the minimum and the maximum number can be generated.
     */
    public int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }

    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 1;
    }

    /**
     * The field.virologist.Virologist moves to a random direction.
     *
     * @param v the field.virologist.Virologist who tries to move
     * @param d the direction he wants to move
     */
    @Override

    public void MoveToField(Virologist v, int d) {
        Skeleton.methodCall(this, "v", "d");
        Field f = v.GetRoute().GetLocation();
        ArrayList<Integer> directions = f.GetDirections();
        int newD = getRandomNumber(0, directions.size());
        Field f2 = f.GetNeighbour(newD);
        f.Remove(v);
        f2.Accept(v);
        v.SetLearnBehavior(new NotLearn());
        v.GetRoute().Add(f2);
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
