package collectables.agent;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.agent.Agent.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//
import collectables.*;
import main.Skeleton;
import assets.virologist.Virologist;
import assets.*;

/** A field.virologist.Virologist can use an collectables.agent.Agent to infect another field.virologist.Virologist (or himself).*/
public abstract class Agent implements Collectable {
	/** The number of turns a field.virologist.Virologist can store the collectables.agent.Agent in his field.Backpack.*/
	protected int warranty;

	/** The number of turns an collectables.agent.Agent stays active on an infected field.virologist.Virologist*/
	protected int duration;

	public int DecreaseWarranty() {
		Skeleton.methodCall(this);
		warranty--;
		Skeleton.methodReturn(this);
		return warranty;
	}

	public int DecreaseDuration() {
		Skeleton.methodCall(this);
		duration--;
		Skeleton.printWithIndent("Duration:" + duration);
		Skeleton.methodReturn(this);
		return duration;
	}
	
	/**
	 * Applies the effects of the collectables.agent.Agent to a field.virologist.Virologist
	 *
	 * @param v the field.virologist.Virologist the collectables.agent.Agent gets applied to
	 * */
	public abstract void Apply(Virologist v);
	
	/**
	 * Removes the effects of the collectables.agent.Agent from a field.virologist.Virologist
	 *
	 * @param v the field.virologist.Virologist the collectables.agent.Agent gets removed from
	 * */
	public void Remove(Virologist v) {
		Skeleton.methodCall(this, "v");
		v.RefreshEffects();
		Skeleton.methodReturn(this);
	}

	/**
	 * Adds the collectables.agent.Agent to a field.virologist.Virologist's field.Backpack
	 *
	 * @param v the field.virologist.Virologist
	 * @param b the field.Backpack
	 * @return true if the adding was successful, false if the adding failed
	 */
	@Override
	public boolean AddToBackpack(Virologist v, Backpack b) {
		Skeleton.methodCall(this, "v", "b");
		v.GetBackpack().Add(this);
		boolean isAdded = Skeleton.yesOrNoInput("Was added?");
		Skeleton.methodReturn(this);
		return isAdded;
	}

	/**
	 * Removes the collectables.agent.Agent from a field.virologist.Virologist's field.Backpack
	 *
	 * @param v the field.virologist.Virologist
	 * @param b the field.Backpack
	 */
	@Override
	public void RemoveFromBackpack(Virologist v, Backpack b) {
		Skeleton.methodCall(this, "v","b");
		v.GetBackpack().Remove(this);
		Skeleton.methodReturn(this);
	}
}
