package collectables.agent;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.agent.Chorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import main.Skeleton;
import assets.virologist.Virologist;
import assets.virologist.behavior.movebehavior.*;

/** collectables.agent.Chorea makes the infected field.virologist.Virologist move to random directions*/
public class Chorea extends Agent {
	/** Constructor*/
	public Chorea(){
		warranty = baseWarranty;
		duration = effectDuration;
	}

	/** The number of turns the collectables.agent.Agent can be used after its creation*/
	private static int baseWarranty = 5;
	private static int effectDuration = 3;
	private static String name;

	/** Applies the effect to the field.virologist.Virologist if there is no stronger effect on him*/
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		if(v.GetMoveBehavior().GetPriority() < 1)
			v.SetMoveBehavior(new RandomMove());
		Skeleton.methodReturn(this);
	}
}
