package assets.field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.field.Normal.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.Backpack;
import collectables.genome.Genome;
import main.Skeleton;
import java.util.ArrayList;

/** A normal field.field.Field*/
public class Normal extends Field implements java.io.Serializable{
	/** Constructor*/
	public Normal(){
		Skeleton.methodCall(this);
		virologists = new ArrayList<>();
		neighbours = new ArrayList<>();
		backpack = new Backpack();
		Skeleton.methodReturn(this);
		neighbours.add(this);
	}

	@Override
	public Genome GetGenome() {
		return null;
	}
	@Override
	public String GetType(){
		return "normal";
	}
}
