package assets.virologist.behavior.pickupbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.pickupbehavior.NotPickUp.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;
import main.Skeleton;
public class NotPickUp implements PickUpBehavior {
    /**
     * Nothing happens
     * @param v the field.virologist.Virologist who wants to pick up something
     * @param c the Collectables the field.virologist.Virologist wants to pick up
     */
    @Override
    public void PickUpCollectable(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v", "c");
        Skeleton.methodReturn(this);
    }
}
