package main;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.Controller.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.field.Field;
import assets.field.Normal;
import assets.virologist.Route;
import assets.virologist.State;
import assets.virologist.Virologist;
import collectables.genome.Genome;

import java.util.ArrayList;

/** Controls the Game and the turns of the players*/
public class Controller {
	private static ArrayList<Field> map;
	private static ArrayList<collectables.genome.Genome>  learnableGenomes;
	private static ArrayList<Virologist> virologists;
	/** the next player*/
	private static int index;

	Controller(){
		map = new ArrayList<>();
		learnableGenomes = new ArrayList<>();
		virologists = new ArrayList<>();
	}
	/** */
	public void Start() {
		Skeleton.methodCall(this);
		Field f = new Normal();
		Virologist v = new Virologist();
		index = 0;
		NextPlayer();
		Skeleton.methodReturn(this);
	}

	public static void TestWin(Virologist v){
		if(v.GetLearnedGenomes() == learnableGenomes.size()){
			End();
		}
	}

	public static void AddLearnableGenome(Genome g){

			if(!learnableGenomes.contains(g))
				learnableGenomes.add(g);


	}


	/** */
	public static void End() {}
	
	/** Calls the next player and him in which directions can he move*/
	public ArrayList<Integer> NextPlayer() {

		Skeleton.methodCall(this);

		index++;
		Virologist v = virologists.get(index);
		if(v.GetState()==State.KILLED){
			virologists.remove(v);
			v = virologists.get(index);

		}
		Route r = v.GetRoute();
		Field f  = r.GetLocation();
		ArrayList<Integer> d = f.GetDirections();
		v.SetState(State.BEFORE_MOVE);
		Skeleton.methodReturn(this);
		return d;
	}

	public void CreateField(String type, String fieldID) {
	}

	public void NeighborFields(String fieldID1, String fieldID2) {
	}

	public void CreateVirologist(String name, String fieldID) {
	}

	public void PutAminoacidOnField(int quantity, String fieldID) {
	}

	public void PutNucleotideOnField(int quantity, String fieldID) {
	}

	public void PutEquipmentOnField(String type, String fieldID) {
	}

	public void GiveAminoacidToVirologist(int quantity, String name) {
	}

	public void GiveNucleotideToVirologist(int quantity, String name) {
	}

	public void GiveEquipmentToVirologist(String type, String name) {
	}

	public void GiveAgentToVirologist(String type, String name) {
	}

	public Virologist GetVirologist(String name) {
		return null;
	}

	public Field GetField(String fieldID) {
		return null;
	}

	public Field GetCurrentField() {
		return null;
	}

	public void MoveVirologistRandomOff(int direction) {
	}

	public void MoveVirologist(int direction) {
	}

	public Virologist GetCurrentVirologist() {
		return null;
	}

	public void DropAminoacid(int quantity) {
	}

	public void DropNucleotide(int quantity) {
	}

	public void DropEquipment(int index) {
	}

	public void TakeAminoacid(int quantity) {
	}

	public void TakeNucleotide(int quantity) {
	}

	public void TakeEquipment(int index) {
	}

	public void StealAminoacid(String name, int quantity) {
	}

	public void StealNucleotide(String name, int quantity) {
	}

	public void StealEquipment(String name, int index) {
	}

	public void LearnGenome() {
	}

	public void TeachGenome(String type, String name) {
	}

	public void CreateAgent(String type) {
	}

	public void InfectVirologist(String name, int index) {
	}

	public void InfectVirologistRandomOff(String name, int index) {
	}

	public void KillVirologist(String name) {
	}

	public void EndTurn() {
	}


}
