package collectables.equipment;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.equipment.Cloak.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;
import assets.virologist.behavior.getinfectedbehavior.MaybeInfected;
import collectables.equipment.Equipment;
import main.Skeleton;

/** The collectables.equipment.Cloak protects the field.virologist.Virologist from Agents with a 82.3% chance*/
public class Cloak extends Equipment {
	private static String name;

	/** Applies the effect to the field.virologist.Virologist if there is no stronger effect on him*/
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		if(v.GetGetInfectedBehavior().GetPriority() < 1)
			v.SetGetInfectedBehavior(new MaybeInfected());
		Skeleton.methodReturn(this);
	}
}
