//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agent.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public abstract class Agent implements Collectable {
	/** */
	private int warranty;
	
	/** */
	private String name;
	
	/** */
	private int effectDuration;
	
	/** */
	private int duration;
	
	/** */
	public int DecreaseWarranty() {
	}
	
	/** */
	public int DecreaseDuration() {
	}
	
	/** */
	public abstract void Apply(Virologist v);
	
	/** */
	public abstract void Remove(Virologist v);
}
