//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aminoacid.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Aminoacid extends Materials {
    /**
     * @param p
     */
    @Override
    public boolean AddToBackpack(Backpack p) {
        return false;
    }

    /**
     * @param p
     */
    @Override
    public void RemoveFromBackpack(Backpack p) {

    }
}
