//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aminoacid.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Aminoacid extends Materials {
    /**
     * @param v
     * @param b
     */
    @Override
    public boolean AddToBackpack(Virologist v, Backpack b) {
        Skeleton.methodCall(this, "v", "b");
        b.Add(this);
        boolean isAdded = Skeleton.yesOrNoInput("Was added?");
        Skeleton.methodReturn(this);
        return isAdded;
    }

    /**
     * @param v
     * @param b
     */
    @Override
    public void RemoveFromBackpack(Virologist v, Backpack b) {
        Skeleton.methodCall(this, "v", "b");
        b.Remove(this);
        Skeleton.methodReturn(this);
    }
}
