//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Backpack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Backpack {
	/** */
	public int capacity;
	
	/** */
	private ArrayList<Nucleotide> nucleotids;
	
	/** */
	private ArrayList<Aminoacid> aminoacids;
	
	/** */
	private ArrayList<Equipment> equipments;
	
	/** */
	public void Add(Equipment e) {
	}
	
	/** */
	public void Add(Aminoacid a) {
	}
	
	/** */
	public void Add(Nucleotide n) {
	}
	
	/** */
	public ArrayList<Equipment> GetEquipments() {
	}
	
	/** */
	public ArrayList<Aminoacid> GetAminos() {
	}
	
	/** */
	public ArrayList<Nucleotide> GetNucleotide() {
	}
	
	/** */
	public void Remove(Equipment e) {
	}
	
	/** */
	public void Remove(Aminoacid a) {
	}
	
	/** */
	public void Remove(Nucleotide n) {
	}
}
