//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Chorea extends Agent {
	/** */
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void Remove(Virologist v) {
		Skeleton.methodCall(this, "v");
		Skeleton.methodReturn(this);
	}

	/**
	 * @param b
	 */
	@Override
	public boolean AddToBackpack(Backpack b) {
		Skeleton.methodCall(this, "b");
		Skeleton.methodReturn(this);
		return false;
	}

	/**
	 * @param b
	 */
	@Override
	public void RemoveFromBackpack(Backpack b) {
		Skeleton.methodCall(this, "b");
		Skeleton.methodReturn(this);
	}
}
