//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cloak.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Cloak extends Equipment {
	/** */
	public void Apply(Virologist v) {
	}
	
	/** */
	public void Remove(Virologist v) {
	}

	/**
	 * @param p
	 */
	@Override
	public boolean AddToBackpack(Backpack p) {
		return false;
	}

	/**
	 * @param p
	 */
	@Override
	public void RemoveFromBackpack(Backpack p) {

	}
}
