//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Collectable.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.nio.file.FileVisitResult;

/** */
interface Collectable {
	/** */
	boolean AddToBackpack(Virologist v, Backpack b);
	
	/** */
	void RemoveFromBackpack(Virologist v, Backpack b);

	void Apply(Virologist v);

	void Remove(Virologist v);
}
