//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controller.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Controller {
	/** */
	private Field map;
	
	/** */
	private ArrayList<Virologist> virologists;
	private static int index;
	/** */
	public void Start() {
		Skeleton.methodCall(this);
		Field f = new Normal();
		Virologist v = new Virologist();
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void End() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public ArrayList<Integer> NextPlayer() {
		Skeleton.methodCall(this);
		index++;
		Virologist v = virologists.get(index);
		Route r = v.GetRoute();
		Field f  = r.GetLocation();
		ArrayList<Integer> d = f.GetDirections();
		v.SetState(State.BEFORE_MOVE);
		Skeleton.methodReturn(this);
		return d;
	}
}
