//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controller.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Controller {
	/** */
	private Field map;
	
	/** */
	private Virologist virologists;
	
	/** */
	public void Start() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void End() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void NextPlayer() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
}
