//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreateBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
interface CreateBehavior {
	/** */
	Agent CreateAgent(Virologist v, Genome g);
}
