//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Create.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

public class Create implements CreateBehavior {
    /**
     * If the Virologist has enough Materials he removes them from his Backpack and creates the Agent.
     *
     * @param v the Virologist who wants to create an agent
     * @param g the Genome he wants to use to create the Agent
     */
    @Override
    public void CreateAgent(Virologist v, Genome g) {
        Skeleton.methodCall(this, "v","g");
        int aminocost = g.getAminoCost();
        int nucleocost = g.getNucleoCost();
        boolean isEnough = v.GetBackpack().EnoughMaterials(aminocost, nucleocost);
        if(isEnough){
            ArrayList<Aminoacid> aminos = v.GetBackpack().GetAminos();
            for(int i = 0; i < g.getAminoCost(); i++){
                v.GetBackpack().Remove(aminos.get(i));
            }
            ArrayList<Nucleotide> nucleos = v.GetBackpack().GetNucleotide();
            for(int i = 0; i < g.getNucleoCost(); i++){
                v.GetBackpack().Remove(nucleos.get(i));
            }
            g.CreateAgent(v);
            v.SetState(State.AFTER_ACTION);
        }
        Skeleton.methodReturn(this);
    }
}
