//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreateBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class CreateBehavior {
	/** */
	public Agent CreateAgent(Genome g) {
	}
}
