//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DropBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
interface DropBehavior {
	/** */
	void DropCollectable(Virologist v, ArrayList<Collectable> c);

}
