//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Drop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Drop implements DropBehavior {

    /**
     * @param c
     */
    @Override
    public void DropCollectable(ArrayList<Collectable> c) {

    }
}
