//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Drop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Drop implements DropBehavior {
    /**
     *
     */
    @Override
    public void DropCollectable() {

    }
}
