//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DropBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class DropBehavior {
	/** */
	public void DropCollectable(Collectable[1..*] c) {
	}
}
