//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Drop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Drop implements DropBehavior {

    /**
     * @param v
     * @param c
     */
    @Override
    public void DropCollectable(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v","c");
        Field f = v.GetRoute().GetLocation();
        for(Collectable collectable: c){
            collectable.RemoveFromBackpack(v, v.GetBackpack());
            collectable.Remove(v);
            f.Add(v, collectable);
        }
        Skeleton.methodReturn(this);
    }
}
