//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DropBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

/** The behavior which decides if the Virologist can drop a few Collectables */
interface DropBehavior {
	/**
	 *
	 * @param v The Virologist who wants to drop
	 * @param c The Collectables he wants to drop
	 */
	void DropCollectable(Virologist v, ArrayList<Collectable> c);
}
