//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Equipment.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public abstract class Equipment implements Collectable {
	/** */
	private String name;
	
	/** */
	public abstract void Apply(Virologist v);
	
	/** */
	public abstract void Remove(Virologist v);

	@Override
	public boolean AddToBackpack(Virologist v) {
		Skeleton.methodCall(this, "b");
		Backpack b = v.GetBackpack();
		b.Add(this);
		if(b.GetEquipments().size() == 3){
			int i = Skeleton.askForInput("Which equipment do you wnat to drop?", 1, 3);
			Equipment e = b.GetEquipments().get(i-1);
			ArrayList<Collectable> list = new ArrayList<Collectable>();
			list.add(e);
			v.DropCollectable(list);
		}
		Skeleton.methodReturn(this);
		return false;
	}

	@Override
	public void RemoveFromBackpack(Virologist v, Backpack b) {
		Skeleton.methodCall(this, "b");
		b.Remove(this);
		Skeleton.methodReturn(this);
	}
}
