//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Equipment.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public abstract class Equipment implements Collectable {
	/** */
	private String name;
	
	/** */
	public abstract void Apply(Virologist v);
	
	/** */
	public abstract void Remove(Virologist v);

	@Override
	public boolean AddToBackpack(Backpack b) {
		Skeleton.methodCall(this, "b");
		Skeleton.methodReturn(this);
		return false;
	}

	@Override
	public void RemoveFromBackpack(Backpack b) {
		Skeleton.methodCall(this, "b");
		Skeleton.methodReturn(this);
	}
}
