//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public abstract class Field {
	/**
	 *
	 */
	protected ArrayList<Virologist> virologists;

	/**
	 *
	 */
	protected ArrayList<Collectable> items;

	/**
	 *
	 */
	protected ArrayList<Field> neighbours;

	/**
	 *
	 */
	protected Backpack backpack;

	/**
	 *
	 */
	public Field GetNeighbour(int d) {
		Skeleton.methodCall(this, "d");
		Field f = neighbours.get(d-1);
		Skeleton.methodReturn(this);
		return f;
	}

	/**
	 *
	 */
	public abstract void Accept(Virologist v);

	/**
	 *
	 */
	public void Remove(Virologist v) {
		Skeleton.methodCall(this, "v");
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void Add(Virologist v, Collectable c) {
		Skeleton.methodCall(this, "c");
		c.AddToBackpack(v, this.backpack);
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void Remove(Virologist v, Collectable c) {
		Skeleton.methodCall(this, "c");
		c.RemoveFromBackpack(v, this.backpack);
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void SetNeighbour(Field f) {
		Skeleton.methodCall(this, "f");
		neighbours.add(f);
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public ArrayList<Integer> GetDirections() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
}