//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public abstract class Field {
	Field(){
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	/**
	 *
	 */
	private Virologist virologists;

	/**
	 *
	 */
	private Collectable items;

	/**
	 *
	 */
	private Field neighbours;

	/**
	 *
	 */
	private Backpack backpack;

	/**
	 *
	 */
	public Field GetNeighbour(int d) {
		Skeleton.methodCall(this, "d");
		Skeleton.methodReturn(this);
		return null;
	}

	/**
	 *
	 */
	public abstract void Accept(Virologist v);

	/**
	 *
	 */
	public void Remove(Virologist v) {
		Skeleton.methodCall(this, "v");
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void Add(Virologist v, Collectable c) {
		Skeleton.methodCall(this, "c");
		c.AddToBackpack(v);
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void Remove(Virologist v, Collectable c) {
		Skeleton.methodCall(this, "c");
		c.RemoveFromBackpack(v, this.backpack);
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public void SetNeighbour(Field f) {
		Skeleton.methodCall(this, "f");
		Skeleton.methodReturn(this);
	}

	/**
	 *
	 */
	public ArrayList<Integer> GetDirections() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
}