//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GenomeChorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//



/** */
public class GenomeChorea extends Genome {
	/** */

	private static int aminocost;
	private static int nucleocost;

	public void CreateAgent(Virologist v) {
		Skeleton.methodCall(this, "v");
		Chorea agent = new Chorea();
		agent.AddToBackpack(v, v.GetBackpack());
		Skeleton.methodReturn(this);
	}

	@Override
	public int getAminoCost() {
		return aminocost;
	}

	@Override
	public int getNucleoCost() {
		return nucleocost;
	}

}
