//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GenomeChorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GenomeChorea extends Genome {
	/** */
	public Agent CreateAgent(Backpack b) { return new Oblivion();}
}
