//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GenomeOblivion.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GenomeOblivion extends Genome {
	/** */
	public void CreateAgent(Virologist v) {
		Skeleton.methodCall(this, "b");
		Oblivion agent = new Oblivion();
		agent.AddToBackpack(v, v.GetBackpack());
		Skeleton.methodReturn(this);
	}
}
