//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Genome.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public abstract class Genome {
	
	/** */
	private String name;
	
	/** */
	public abstract void CreateAgent(Virologist v);

	public abstract int getAminoCost();

	public abstract int getNucleoCost();
}
