//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GenomeParalysis.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GenomeParalysis extends Genome {
	/** */
	public Agent CreateAgent(Backpack b) {
		Skeleton.methodCall(this, "b");
		Skeleton.methodReturn(this);
		return new Oblivion();}
}
