//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GenomeProtection.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

/** The GenomeChorea is used to create the Protection Agent*/
public class GenomeProtection extends Genome {
	private static int aminocost;
	private static int nucleocost;
	private static String name;

	/**
	 * Creates a Protection Agent and puts it into the Backpack of the Virologist that created it
	 *
	 * @param v the Virologist who creates the Agent
	 */
	public void CreateAgent(Virologist v) {
		Skeleton.methodCall(this, "v");
		Protection agent = new Protection();
		agent.AddToBackpack(v, v.GetBackpack());
		Skeleton.methodReturn(this);
	}
	@Override
	public int getAminoCost() {
		return aminocost;
	}

	@Override
	public int getNucleoCost() {
		return nucleocost;
	}
}
