//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetInfected.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GetInfected implements GetInfectedBehavior {
    /**
     *
     */
    @Override
    public int GetPriority() {
        return 0;
    }

    /**
     * @param v1
     * @param v2
     * @param a
     */
    @Override
    public void GetInfected(Virologist v1, Virologist v2, Agent a) {
        Skeleton.methodCall(this, "v1", "v2", "a");
        a.Apply(v2);
        v2.GetBackpack().AddApplied(a);
        Skeleton.methodReturn(this);
    }
}
