//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetInfectedBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
interface GetInfectedBehavior {
	/** */
	int priority = 0;
	
	/** */
	int GetPriority();
	
	/** */
	void GetInfected(Virologist v1, Virologist v2, Agent a);
}
