//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetInfectedBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GetInfectedBehavior {
	/** */
	private int priority;
	
	/** */
	public int GetPriority() {
	}
	
	/** */
	public void GetInfected(Virologist v1, Virologist v2, Agent a) {
	}
}
