//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetStolen.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class GetStolen implements GetStolenBehavior {
}
