//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetStolenBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
interface GetStolenBehavior {
	/** */
	boolean GetStolenFrom(Collectable[1..*] c);
}
