//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GetStolenBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
interface GetStolenBehavior {
	/** */
	boolean GetStolenFrom(ArrayList<Collectable> c);
}
