//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gloves.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Gloves extends Equipment {
	/** */
	public void Apply(Virologist v) {
	}
	
	/** */
	public void Remove(Virologist v) {
	}
}
