//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InfectBack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

public class InfectBack implements GetInfectedBehavior {
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 3;
    }

    /**
     * v1 will get infected regardless of his protection level.
     *
     * @param v1 the Virologist who wants to infect
     * @param v2 the target of the action
     * @param a the Agents v1 wants to infect v2 with
     */
    @Override
    public void GetInfected(Virologist v1, Virologist v2, Agent a) {
        Skeleton.methodCall(this, "v1", "v2", "a");
        v1.GetInfected(v2, a);
        Skeleton.methodReturn(this);
    }
}
