//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InfectBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class InfectBehavior {
	/** */
	public void Infect(Virologist v1, Virologist v2, Agent a) {
	}
}
