//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Learn.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Learn implements LearnBehavior {
    /**
     *
     */
    @Override
    public void Learn() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
    }
}
