//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LearnBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

/** The behavior which decides if the Virologist can learn a Genome */
interface LearnBehavior {
	/**
	 *
	 * @param v the Virologist who wants to learn the Genome
	 */
	void Learn(Virologist v);
}
