//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LearnBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class LearnBehavior {
	/** */
	public void Learn() {
	}
}
