//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Materials.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

/** The Materials are the things that the Agents are made of*/
public abstract class Materials implements Collectable {
    /** Nothing happens*/
    @Override
    public void Apply(Virologist v) {
        Skeleton.methodCall(this, "v");
        Skeleton.methodReturn(this);
    }

    /** Nothing happens*/
    @Override
    public void Remove(Virologist v) {
        Skeleton.methodCall(this, "v");
        Skeleton.methodReturn(this);
    }
}
