//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Materials.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public abstract class Materials implements Collectable {
    @Override
    public void Apply(Virologist v) {

    }

    @Override
    public void Remove(Virologist v) {

    }
}
