//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class MoveBehavior {
	/** */
	private int priority;
	
	/** */
	public int GetPriority() {
	}
	
	/** */
	public void Move(Virologist v, int d) {
	}
}
