//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
interface MoveBehavior {
	/** */
	int priority = 0;
	
	/** */
	int GetPriority();
	
	/** */
	void Move(Virologist v, int d);
}
