//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Move.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Move implements MoveBehavior {
    /**
     *
     */
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 0;
    }

    /**
     * @param v
     * @param d
     */
    @Override
    public void Move(Virologist v, int d) {

        Skeleton.methodCall(this, "v", "d");
        Field f = v.GetRoute().GetLocation();
        Field f2 = f.GetNeighbour(d);
        f.Remove(v);
        f2.Accept(v);
        v.GetRoute().Add(f2);
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
