//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Normal.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Normal extends Field {
	/** */
	public void Accept(Virologist v) {
	}
}
