//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotCreate.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

public class NotCreate implements CreateBehavior {
    /**
     * Nothing happens
     * 
     * @param v the Virologist who wants to create an agent
     * @param g the Genome he wants to use to create the Agent
     */
    @Override
    public void CreateAgent(Virologist v, Genome g) {
        Skeleton.methodCall(this, "v","g");
        Skeleton.methodReturn(this);
    }
}
