//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotCreate.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class NotCreate implements CreateBehavior {
    /**
     * @param g
     */
    @Override
    public Agent CreateAgent(Genome g) {
        return null;
    }
}
