//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotCreate.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class NotCreate implements CreateBehavior {
    /**
     * @param g
     */
    @Override
    public void CreateAgent(Virologist v, Genome g) {
        Skeleton.methodCall(this, "g");
        Skeleton.methodReturn(this);
    }
}
