//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class NotDrop implements DropBehavior {
    /**
     *
     */
    @Override
    public void DropCollectable(ArrayList<Collectable> c) {

    }
}
