//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

public class NotDrop implements DropBehavior {
    /**
     * Nothing happens.
     *
     * @param v The Virologist who wants to drop
     * @param c The Collectables he wants to drop
     */
    @Override
    public void DropCollectable(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v","c");
        Skeleton.methodReturn(this);
    }
}
