//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotGetStolen.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class NotGetStolen implements GetStolenBehavior {
    /**
     *
     */
    @Override
    public boolean GetStolenFrom(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "c");
        Skeleton.methodReturn(this);
        return false;
    }
}
