//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotInfect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class NotInfect implements InfectBehavior {
}
