//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotInfect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

public class NotInfect implements InfectBehavior {
    /**
     * Nothing happens.
     *
     * @param v1 the Virologist who wants to infect
     * @param v2 the target of the action
     * @param a the Agents v1 wants to infect v2 with
     */
    @Override
    public void Infect(Virologist v1, Virologist v2, Agent a) {
        Skeleton.methodCall(this, "v1", "v2", "a");
        Skeleton.methodReturn(this);
    }
}
