//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

public class NotMove implements MoveBehavior {
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 2;
    }

    /**
     * Nothing happens.
     *
     * @param v the Virologist who tries to move
     * @param d the direction he wants to move
     */
    @Override
    public void Move(Virologist v, int d) {
        Skeleton.methodCall(this, "v", "d");
        Field f = v.GetRoute().GetLocation();
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
