//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class NotMove implements MoveBehavior {
    /**
     *
     */
    @Override
    public int GetPriority() {
        return 0;
    }

    /**
     * @param v
     * @param d
     */
    @Override
    public void Move(Virologist v, int d) {

    }
}
