//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotPickUp.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

public class NotPickUp implements PickUpBehavior {
    /**
     * Nothing happens
     * @param v the Virologist who wants to pick up something
     * @param c the Collectables the Virologist wants to pick up
     */
    @Override
    public void PickUpCollectable(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v", "c");
        Skeleton.methodReturn(this);
    }
}
