//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotPickUp.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class NotPickUp implements PickUpBehavior {
    /**
     * @param v
     */
    @Override
    public void PickUpCollectable(Virologist v) {

    }
}
