//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotSteal.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class NotSteal implements StealBehavior {
    /**
     * @param v
     */
    @Override
    public void Steal(Virologist v1, Virologist v2, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v", "c");
        Skeleton.methodReturn(this);
    }
}
