//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nucleotide.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Nucleotide extends Materials{
    @Override
    public boolean AddToBackpack(Virologist v) {
        Skeleton.methodCall(this, "b");
        Skeleton.methodReturn(this);return false;
    }

    @Override
    public void RemoveFromBackpack(Virologist v, Backpack b) {
        Skeleton.methodCall(this,"b");
        b.Remove(this);
        Skeleton.methodReturn(this);
    }

    @Override
    public void Apply(Virologist v) {

    }

    @Override
    public void Remove(Virologist v) {

    }
}
