//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nucleotide.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Nucleotide extends Materials{
    @Override
    public boolean AddToBackpack(Virologist v, Backpack b) {
        Skeleton.methodCall(this, "b");
        boolean isAdded = Skeleton.yesOrNoInput("Was added?");
        Skeleton.methodReturn(this);
        return isAdded;
    }

    @Override
    public void RemoveFromBackpack(Virologist v, Backpack b) {
        Skeleton.methodCall(this,"v", "b");
        b.Remove(this);
        Skeleton.methodReturn(this);
    }
}
