//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Oblivion.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Oblivion extends Agent {
	Oblivion(){
		warranty = baseWarranty;
		duration = effectDuration;
	}
	private static int baseWarranty;
	private static int effectDuration;
	/** */
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		v.ForgetGenome();
		Skeleton.methodReturn(this);
	}
}
