//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Paralysis.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

/** The Virologist can not do anything. Other Virologists can steal from him*/
public class Paralysis extends Agent {
	/** Constructor*/
	Paralysis(){
		warranty = baseWarranty;
		duration = effectDuration;
	}

	/** The number of turns the Agent can be used after its creation*/
	private static int baseWarranty;
	private static int effectDuration;
	private static String name;

	/** Applies the effects on a Virologist*/
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		if(v.GetMoveBehavior().GetPriority() < 2)
			v.SetMoveBehavior(new NotMove());
		v.SetCreateBehavior(new NotCreate());
		v.SetLearnBehavior(new NotLearn());
		v.SetStealBehavior(new NotSteal());
		v.SetPickUpBehavior(new NotPickUp());
		v.SetInfectBehavior(new NotInfect());
		v.SetDropBehavior(new NotDrop());
		v.SetGetStolenBehavior(new GetStolen());
		Skeleton.methodReturn(this);
	}
}
