//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Paralysis.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Paralysis extends Agent {
	Paralysis(){
		warranty = baseWarranty;
		duration = effectDuration;
	}
	private static int baseWarranty;
	private static int effectDuration;
	/** */
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		v.SetMoveBehavior(new NotMove());
		v.SetCreateBehavior(new NotCreate());
		v.SetLearnBehavior(new NotLearn());
		v.SetStealBehavior(new NotSteal());
		v.SetPickUpBehavior(new NotPickUp());
		v.SetInfectBehavior(new NotInfect());
		v.SetDropBehavior(new NotDrop());
		v.SetGetStolenBehavior(new GetStolen());
		Skeleton.methodReturn(this);
	}
}
