//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PickUpBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

/** The behavior which decides if the Virologist can pick up a Collectable */
interface PickUpBehavior {
	/**
	 *
	 * @param v the Virologist who wants to pick up something
	 * @param c the Collectables the Virologist wants to pick up
	 */
	void PickUpCollectable(Virologist v, ArrayList<Collectable> c);
}
