//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PickUpBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class PickUpBehavior {
	/** */
	public void PickUpCollectable(Virologist v, Collectable[1..*] c) {
	}
}
