//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PickUpBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
interface PickUpBehavior {
	/** */
	void PickUpCollectable(Virologist v, Collectable[1..*] c);
}
