//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PickUp.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

public class PickUp implements PickUpBehavior {
    /**
     * The Virologist picks up the Collectables and sets the state to AFTER_ACTION
     *
     * @param v the Virologist who wants to pick up something
     * @param c the Collectables the Virologist wants to pick up
     */
    @Override
    public void PickUpCollectable(Virologist v, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v", "c");
        for(Collectable collectable: c){
            v.GetRoute().GetLocation().Remove(v, collectable);
            boolean isAdded = collectable.AddToBackpack(v, v.GetBackpack());
            collectable.Apply(v);
            if(!isAdded){
                v.SetState(State.AFTER_ACTION);
                break;
            }
        }
        v.SetState(State.AFTER_ACTION);
        Skeleton.methodReturn(this);
    }
}
