//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Protection.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

/** The Virologist can not get infected by other Virologists*/
public class Protection extends Agent {
	/** Constructor*/
	Protection(){
		warranty = baseWarranty;
		duration = effectDuration;
	}

	/** The number of turns the Agent can be used after its creation*/
	private static int baseWarranty;
	private static int effectDuration;
	private static String name;

	/** Applies the effect to the Virologist if there is no stronger effect on him*/
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		if(v.GetGetInfectedBehavior().GetPriority() < 2)
			v.SetGetInfectedBehavior(new NotInfected());
		Skeleton.methodReturn(this);
	}
}
