//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Protection.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Protection extends Agent {
	/** */
	public void Apply(Virologist v) {
	}
	
	/** */
	public void Remove(Virologist v) {
	}
}
