//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RandomMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

/** */
public class RandomMove implements MoveBehavior {

    public int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }
    /**
     *
     */
    @Override
    public int GetPriority() {
        Skeleton.methodCall(this);
        Skeleton.methodReturn(this);
        return 1;
    }

    /**
     * @param v
     * @param d
     */
    @Override
    public void Move(Virologist v, int d) {
        Skeleton.methodCall(this, "v", "d");
        Field f = v.GetRoute().GetLocation();
        ArrayList<Integer> directions = f.GetDirections();
        int newD = getRandomNumber(0, directions.size());
        Field f2 = f.GetNeighbour(newD);
        f.Remove(v);
        f2.Accept(v);
        v.SetLearnBehavior(new NotLearn());
        v.GetRoute().Add(f2);
        v.SetState(State.BEFORE_ACTION);
        Skeleton.methodReturn(this);
    }
}
