//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RandomMove.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class RandomMove implements MoveBehavior {
}
