//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Route.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Route {
	Route(){
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	/** */
	public Field fields;
	
	/** */
	public Field GetLocation() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public void Add(Field f) {
		Skeleton.methodCall(this, "f");
		Skeleton.methodReturn(this);
	}
}
