//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Route.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Route {
	/** */
	public Field fields;
	
	/** */
	//public Field GetLocation() {}
	
	/** */
	public void Add(Field f) {
	}
}
