//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Sack extends Equipment {
	private static int enhanced = 30;
	private static  int normal = 20;
	/** */
	public void Apply(Virologist v) {
		Skeleton.methodCall(this, "v");
		v.GetBackpack().setCapacity(enhanced);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void Remove(Virologist v) {
		Skeleton.methodCall(this, "v");
		v.GetBackpack().setCapacity(normal);
		Skeleton.methodReturn(this);
	}
}
