//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Shelter extends Field {
	Shelter(){
		Skeleton.methodCall(this);
		this.virologists = new ArrayList<Virologist>();
		this.items = new ArrayList<Collectable>();
		this.neighbours = new ArrayList<Field>();
		backpack = new Backpack();
		Skeleton.methodReturn(this);
	}
	/** */
	public void Accept(Virologist v) {
		Skeleton.methodCall(this, "v");
		Skeleton.methodReturn(this);
	}
}
