//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Shelter extends Field {
	Shelter(){
		Skeleton.methodCall(this);
		this.virologists = new ArrayList<>();
		this.neighbours = new ArrayList<>();
		backpack = new Backpack();
		Skeleton.methodReturn(this);
	}
}
