//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Skeleton.java
//  @ Date : 2022. 03. 23.
//  @ Author :
//
//

public class Skeleton {
    private static int tabNum = 0;

    public Skeleton(){
    }

    public static void main(String[] args){
        Skeleton skeleton = new Skeleton();
        skeleton.run();
    }

    public void indent(){
    }

    public void methodCall(){

    }

    public void methodReturn(){

    }

    public void run(){

    }
}
