//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steal.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class Steal implements StealBehavior {
    /**
     * @param v
     */
    @Override
    public void Steal(Virologist v) {

    }
}
