//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StealBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
interface StealBehavior {
	/** */
	void Steal(Virologist v, ArrayList<Collectable> c);
}
