//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steal.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Steal implements StealBehavior {
    /**
     *
     */
    @Override
    public void Steal(Virologist v1,Virologist v2, ArrayList<Collectable> c) {
        Skeleton.methodCall(this, "v1", "v2", "c");
        boolean isStolen = v2.GetStolenFrom(c);
        if(isStolen){
            v1.PickUpCollectable(c);
            v1.SetState(State.AFTER_ACTION);
        }
        Skeleton.methodReturn(this);
    }
}
