//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirologistBackpack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class VirologistBackpack extends Backpack {
	/** */
	private ArrayList<Agent> agents;
	
	/** */
	private ArrayList<Agent> appliedAgents;
	
	/** */
	public void Add(Equipment e) {
		Skeleton.methodCall(this, "e");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void Add(Agent a) {
		Skeleton.methodCall(this, "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void AddApplied(Agent a) {
		Skeleton.methodCall(this, "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public ArrayList<Agent> GetAgents() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public ArrayList<Agent> GetAppliedAgents() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public void Remove(Agent a) {
		Skeleton.methodCall(this, "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void RemoveApplied(Agent a) {
		Skeleton.methodCall(this, "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void Remove(Equipment e) {
		Skeleton.methodCall(this, "e");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void DecreaseWarranties() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public boolean EnoughMaterials(int a, int n) {
		Skeleton.methodCall(this, "a", "n");
		Skeleton.methodReturn(this);
		return false;
	}
}
