//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirologistBackpack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class VirologistBackpack extends Backpack {
	/** */
	private ArrayList<Agent> agents;
	
	/** */
	private ArrayList<Agent> appliedAgents;
	
	/** */
	public void Add(Equipment e) {
	}
	
	/** */
	public void Add(Agent a) {
	}
	
	/** */
	public void AddApplied(Agent a) {
	}
	
	/** */
	//public ArrayList<Agent> GetAgents() {}
	
	/** */
	//public ArrayList<Agent> GetAppliedAgents() {}
	
	/** */
	public void Remove(Agent a) {
	}
	
	/** */
	public void RemoveApplied(Agent a) {
	}
	
	/** */
	public void Remove(Equipment e) {
	}
	
	/** */
	public void DecreaseWarranties() {
	}
	
	/** */
	//public boolean EnoughMaterials(int a, int n) {}
}
