//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//


import java.util.ArrayList;

/** */
public class Virologist {
	/** */
	private State state;
	
	/** */
	private String name;
	
	/** */
	private VirologistBackpack backPack;
	
	/** */
	private Route route;
	
	/** */
	private Genome learnedGenomes;
	
	/** */
	private PickUpBehavior pickUpBehavior;
	
	/** */
	private CreateBehavior createBehavior;
	
	/** */
	private LearnBehavior learnBehavior;
	
	/** */
	private StealBehavior stealBehavior;
	
	/** */
	private MoveBehavior moveBehavior;
	
	/** */
	private GetInfectedBehavior getInfectedBehavior;
	
	/** */
	private DropBehavior dropBehavior;
	
	/** */
	private InfectBehavior infectBehavior;
	
	/** */
	private GetStolenBehavior getStolenBehavior;
	
	/** */
	public void Move(int d) {
		Skeleton.methodCall(this, "d");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void PickUpCollectable(ArrayList<Collectable> c) {
		Skeleton.methodCall(this, "c");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void DropCollectable(ArrayList<Collectable> c) {
		Skeleton.methodCall(this, "c");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void Steal(Virologist v, ArrayList<Collectable> c) {
		Skeleton.methodCall(this, "c");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public boolean GetStolenFrom(ArrayList<Collectable> c) {
		Skeleton.methodCall(this,"c");
		Skeleton.methodReturn(this);
		return false;}
	
	/** */
	public void Infect(Virologist v, Agent a) {
		Skeleton.methodCall(this, "v", "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public boolean Add(Genome g) {
		Skeleton.methodCall(this, "g");
		Skeleton.methodReturn(this);
		return false;}
	
	/** */
	public void Learn() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void ListCollectables() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public Agent CreateAgent(Genome g) {
		Skeleton.methodCall(this, "g");
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public void GetInfected(Virologist v, Agent a) {
		Skeleton.methodCall(this, "v", "a");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void SetState(State s) {
		Skeleton.methodCall(this, "s");
		Skeleton.methodReturn(this);
	}
	
	/** */
	public State GetState() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public Route GetRoute() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
		return null;
	}
	
	/** */
	public void EndTurn() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void RefreshEffects() {
		Skeleton.methodCall(this);
		Skeleton.methodReturn(this);
	}
	
	/** */
	public void ForgetGenome(Genome g) {
		Skeleton.methodCall(this, "g");
		Skeleton.methodReturn(this);
	}
}
