//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VirologistBackpack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//




/** */
public class VirologistBackpack extends Backpack implements Backpack {
	/** */
	private Agent agents;
	
	/** */
	private Agent appliedAgents;
	
	/** */
	public void Add(Equipment e) {
	}
	
	/** */
	public void Add(Agent a) {
	}
	
	/** */
	public void AddApplied(Agent a) {
	}
	
	/** */
	public Agent[0..*] GetAgents() {
	}
	
	/** */
	public Agent[0..*] GetAppliedAgents() {
	}
	
	/** */
	public void Remove(Agent a) {
	}
	
	/** */
	public void RemoveApplied(Agent a) {
	}
	
	/** */
	public void Remove(Equipment e) {
	}
	
	/** */
	public void DecreaseWarranties() {
	}
	
	/** */
	public bool EnoughMaterials(int a, int n) {
	}
}
